{% set name = "stern" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stern/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4be6932a97da0e36aea1c6cffaad559caea19f4948dcef8dc1686d5c2e0d3045

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.22
    - file  # [not win]
    - go-licenses >=1.6.0

test:
  commands:
    - stern -v
    - stern --help
    - stern --completion=bash

about:
  home: https://github.com/stern/stern
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: Multi pod and container log tailing for Kubernetes
  description: |
    Stern allows you to tail multiple pods on Kubernetes and multiple containers within the pod. Each result is color coded for quicker debugging.
    Fork of discontinued https://github.com/wercker/stern .
  doc_url: https://github.com/stern/stern
  dev_url: https://github.com/stern/stern

extra:
  recipe-maintainers:
    - manics
