{% set name = "stern" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stern/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1caf2a6f1492f763bb6a961d4c8af8cd3ab1952d216b0ab21059fe1a1d4426db

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.19
    - file  # [not win]
    - go-licenses >=0.0.44

test:
  commands:
    - stern -v
    - stern --help
    - stern --completion=bash

about:
  home: https://github.com/stern/stern
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: Multi pod and container log tailing for Kubernetes
  description: |
    Stern allows you to tail multiple pods on Kubernetes and multiple containers within the pod. Each result is color coded for quicker debugging.
    Fork of discontinued https://github.com/wercker/stern .
  doc_url: https://github.com/stern/stern
  dev_url: https://github.com/stern/stern

extra:
  recipe-maintainers:
    - manics
